# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('favorites', models.ManyToManyField(related_name='userFaves', to='loginReg.User')),
                ('userAdded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAdds', to='loginReg.User')),
            ],
        ),
    ]
